services:
  - type: web
    name: organaizer-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: google/gemini-2.5-pro-exp-03-25:free@server
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true 