services:
  - type: web
    name: organaizer-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: google/gemini-2.5-pro-exp-03-25:free
    plan: free